20220208/BizimMarket/BizimMarket/Areas/Admin/Controllers/UrunlerController.cs
using BizimMarket.Areas.Admin.Models;
using BizimMarket.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BizimMarket.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UrunlerController : Controller
    {
        private readonly BizimMarketContext _db;
        private readonly IWebHostEnvironment _env;

        public UrunlerController(BizimMarketContext db, IWebHostEnvironment env)
        {
            _db = db;
            _env = env;
        }

        public IActionResult Index()
        {
            return View(_db.Urunler.Include(x => x.Kategori).ToList());
        }

        public IActionResult Yeni()
        {
            KategorileriYukle();
            return View();
        }
        
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Yeni(YeniUrunViewModel vm)
        {
            if (ModelState.IsValid)
            {
                string dosyaAdi = ResimYukle(vm.Resim);

                Urun urun = new Urun()
                {
                    Ad = vm.Ad,
                    Fiyat = vm.Fiyat.Value,
                    KategoriId = vm.KategoriId.Value,
                    ResimYolu = dosyaAdi
                };
                _db.Add(urun);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return KategorileriYukle();
        }



        public IActionResult Duzenle(int id)
        {
            var urun = _db.Urunler.Find(id);
            if (urun == null) return NotFound();
            KategorileriYukle();
            var model = new DuzenleUrunViewModel()
            {
                Ad = urun.Ad,
                Fiyat = urun.Fiyat,
                KategoriId = urun.KategoriId,
                ResimYolu = urun.ResimYolu
            };
            return View(model);
        }

        [HttpPost, AutoValidateAntiforgeryToken]
        public IActionResult Duzenle(DuzenleUrunViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var urun = _db.Urunler.Find(vm.Id);
                urun.Ad = vm.Ad;
                urun.Fiyat = vm.Fiyat.Value;
                urun.KategoriId = vm.KategoriId.Value;
                if (vm.Resim != null)
                {
                    ResimSil(urun.ResimYolu); //Eski resmi sil
                    urun.ResimYolu = ResimYukle(vm.Resim); // gelen resmi yükle.
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            KategorileriYukle();
            return View(vm);
        }


        public IActionResult Sil(int id)
        {
            Urun urun = _db.Urunler.Find(id);
            if (urun == null) return NotFound();

            ResimSil(urun.ResimYolu); // Fiziksel olarak silmek

            _db.Urunler.Remove(urun);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        private IActionResult KategorileriYukle()
        {
            ViewBag.Kategoriler = _db.Kategoriler
                .Select(x => new SelectListItem(x.Ad, x.Id.ToString()))
                .ToList();
            return View();
        }
        private string ResimYukle(IFormFile file)
        {
            string dosyaAdi = null;
            if (file != null)
            {
                dosyaAdi = Guid.NewGuid() + Path.GetExtension(file.FileName);
                string kaydetmeYolu = Path.Combine(_env.WebRootPath, "img", "urunler", dosyaAdi);
                using (var fs = new FileStream(kaydetmeYolu, FileMode.Create))
                {
                   file.CopyTo(fs);
                }
            }

            return dosyaAdi;
        }

        private void ResimSil(string dosyaYolu)
        {
            if (dosyaYolu == null) return;
            string silmeYolu = Path.Combine(_env.WebRootPath, "img", "urunler", dosyaYolu);
            try
            {
                System.IO.File.Delete(silmeYolu);
            }
            catch (Exception)
            {
            }
        }
    }
}

20220208/BizimMarket/BizimMarket/Areas/Admin/Views/Urunler/Duzenle.cshtml
@model DuzenleUrunViewModel
@{
    ViewBag.Title = "Ürün Düzenle";
}
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <div class="mb-3">
                <label asp-for="Ad" class="form-label">Ad</label>
                <input asp-for="Ad" type="text" class="form-control" />
                <span asp-validation-for="Ad" class="form-text"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Fiyat" class="form-label">Fiyat</label>
                <input asp-for="Fiyat" type="text" class="form-control" />
                <span asp-validation-for="Fiyat" class="form-text"></span>
            </div>

            <div class="mb-3">
                <label asp-for="KategoriId" class="form-label">Kategori</label>
                <select asp-for="KategoriId" asp-items="ViewBag.Kategoriler" class="form-select">
                    <option value="">Seçiniz</option>
                </select>
                <span asp-validation-for="KategoriId" class="form-text"></span>
            </div>

            <div class="mb-3">
                <input type="hidden" asp-for="ResimYolu" />
                <label asp-for="Resim" class="form-label">Ürün Görseli</label>
                <div class="mb-2">
                    <img id="imgOnizleme" class="img-thumbnail" src="~/img/urunler/@(Model.ResimYolu ?? "default.jpg") " width="100" alt="Alternate Text" />
                </div>
                <input type="file" asp-for="Resim" class="form-control" />
                <span asp-validation-for="Resim" class="form-text"></span>
            </div>

            <button class="btn btn-primary">Ekle</button>
        </form>
    </div>
</div>

<script>
    var imgOnizleme = document.getElementById("imgOnizleme");
    var inputResim = document.getElementById("Resim");
    inputResim.onchange = event => {
        var file = inputResim.files[0];
        if (file) {
            imgOnizleme.src = URL.createObjectURL(file);
        }
    }
</script> 

20220208/BizimMarket/BizimMarket/Areas/Admin/Views/Urunler/Index.cshtml
@model List<Urun>
@{
    ViewData["Title"] = "Ürünler";
}

<a asp-controller="Urunler" asp-action="Yeni">Yeni Ürün</a>

<table class="table table-admin">
    <thead>
        <tr>
            <th></th>
            <th>Id</th>
            <th>Ad</th>
            <th>Fiyat</th>
            <th>Kategori</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td><img src="~/img/urunler/@(item.ResimYolu ?? "default.png")" width="50" /></td>
                <td>@item.Id</td>
                <td>@item.Ad</td>
                <td>₺@item.Fiyat.ToString("n2")</td>
                <td>@item.Kategori.Ad</td>
                <td>
                    <form class="d-inline-block" id="sil-@item.Id" asp-controller="Urunler" asp-action="Sil" method="post" >
                        <input type="hidden" name="Id" value="@item.Id" />
                        <button onclick="sil(@item.Id)" type="button" class="btn btn-sm btn-outline-danger"><i class="fas fa-trash"></i></button>
                    </form>
                    <a class="btn btn-outline-info btn-sm" asp-action="Duzenle" asp-controller="Urunler" asp-route-id="@item.Id"><i class="fas fa-edit"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>
@section Scripts{
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        function sil(id) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    document.getElementById("sil-" + id).submit();
                }
            })
        }
    </script>
}

20220208/BizimMarket/BizimMarket/Areas/Admin/Views/Urunler/Yeni.cshtml
@model YeniUrunViewModel 
@{
    ViewBag.Title = "Yeni Ürün";
}
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div class="mb-3">
                <label asp-for="Ad" class="form-label">Ad</label>
                <input asp-for="Ad" type="text" class="form-control" />
                <span asp-validation-for="Ad" class="form-text"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Fiyat" class="form-label">Fiyat</label>
                <input asp-for="Fiyat" type="text" class="form-control" />
                <span asp-validation-for="Fiyat" class="form-text"></span>
            </div>

            <div class="mb-3">
                <label asp-for="KategoriId" class="form-label">Kategori</label>
                <select asp-for="KategoriId" asp-items="ViewBag.Kategoriler" class="form-select">
                    <option value="">Seçiniz</option>
                </select>
                <span asp-validation-for="KategoriId" class="form-text"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Resim" class="form-label">Ürün Görseli</label>
                <input type="file" asp-for="Resim" class="form-control" />
                <span asp-validation-for="Resim" class="form-text"></span>
            </div>

            <button class="btn btn-primary">Ekle</button>
        </form>
    </div>
</div>